name: Print action info
run-name: ${{ github.actor }}  is testing out GitHub Actions
#on: [branch_protection_rule,check_run,check_suite,create,delete,deployment,deployment_status,discussion,discussion_comment,fork,gollum,issue_comment,issues,label,merge_group,milestone,page_build,project,project_card,project_column,public,pull_request,issue_comment,pull_request_review,pull_request_review_comment,pull_request_target,push,registry_package,release,repository_dispatch,schedule,status,watch,workflow_call,workflow_dispatch]
on: 
  pull_request_target:
    branches:
      - 'main'
    types: [assigned,unassigned,labeled,unlabeled,opened,edited,closed,reopened,synchronize,converted_to_draft,locked,unlocked,enqueued,dequeued,milestoned,demilestoned,ready_for_review,review_requested,review_request_removed,auto_merge_enabled,auto_merge_disabled]
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "EVENT_NAME $EVENT_NAME"
          python ./script/cmd.py


